### ISSUE TITLE
Branding/appearance for site and form

### ISSUE THREAD

**Issue by jaceybee** [clickonetwo/whisper#16]
Can you please add the ClickOneTwo logo to the Whisper website? Also, we need to create a Whisper logo/icon (which might replace the current app icon). One suggestion: either turn the lines of the speech bubble white or fill the black-lined bubble with white. That logo would then go on the support form and website.

**Comment by brotskydotcom2** [comment]
> Can you please add the ClickOneTwo logo to the Whisper website?

@jaceybee Do you mean "add the Whisper logo to the Whisper website?"

I've updated the app icon as you suggested (with a white instead of black dashed line).  You should see that in the next build.

**Comment by brotskydotcom2** [comment]
I've updated the branding on the form to say "\<Whisper logo\> by ClickOneTwo".  Take a look.

**Comment by jaceybee** [comment]
The font I used in the Canva mock-up we looked at today is Sensa Serif, by FontFabric
https://xfonts.pro/fonts/sensa_serif-regular
