### ISSUE TITLE
"Require Bluetooth listeners to pair" rename/move

### ISSUE THREAD

**Issue by jaceybee** [clickonetwo/whisper#27]
If this option can be turned on by Listeners as well as Whisperers, then it should be called "Require Bluetooth pairing." If it's only for Whisperers, it should probably be in the Whisper settings.

**Comment by brotskydotcom2** [comment]
I think this is just a naming issue.  This setting is an app-level setting which only applies to when you're whispering, as opposed to the "Listener shows latest whispers on top/on bottom" which clearly only applies when you're listening.  This is not something you're going to need change in the middle of a session, which is what all the "whisper settings" are.  In the same way that the "Listener shows latest whispers..." setting, I am going to rename this to "Whisperer requires Bluetooth listeners to pair".

**Comment by jaceybee** [comment]
I think that wording works! But would it be possible to make it look more
like the Listener only setting? So it would be like:
Whisperer requires Bluetooth pairing: [yes/no] (in a dropdown)

**Comment by brotskydotcom2** [comment]
@jaceybee Apple interface guidelines require using a toggle rather than a yes/no menu.  So I can't make the change you're suggesting.

**Comment by jaceybee** [comment]
@clickonetwo Would it be possible to make it "Whisperer requires Bluetooth
pairing" and then the toggle? Or does Apple also control that?
